---
title: "Titanic suvivor prediction"
output:
  html_document: 
    toc: true
    toc_float: false
  pdf_document: default
  md_document:
    variant:
      markdown_github
  revealjs::revealjs_presentation: 
    theme: league
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## 

## 加载训练数据集
通过如下代码加载训练数据集并存于train中

```{r "Loading necessary libraries", echo=FALSE, results='hide', message=FALSE}
library(readr) # File read / write
library(ggplot2) # Data visualization
library(ggthemes) # Data visualization
library(scales) # Data visualization
library(plyr)
library(stringr) # String manipulation
library(InformationValue) # IV / WOE calculation
library(MLmetrics) # Mache learning metrics.e.g. Recall, Precision, Accuracy, AUC
library(rpart) # Decision tree utils
library(randomForest) # Random Forest
library(dplyr) # Data manipulation
library(e1071) # SVM
library(Amelia) # Missing value utils
library(party) # Conditional inference trees
library(gbm) # AdaBoost
library(class) # KNN
```


```{r echo=TRUE, results='hide', message=FALSE, cache=TRUE}
train <- read_csv("train.csv")
test <- read_csv("test.csv")
full <- bind_rows(train, test)
train.records <- nrow(train)
full$Fare[is.na(full$Fare)] <- median(full$Fare[!is.na(full$Fare)])
```




```{r}
full$Title <- gsub('(.*, )|(\\..*)', '', full$Name)
full$Title[full$Title %in% c('Mlle', 'Ms', 'Lady')] <- 'Miss'
full$Title[full$Title %in% c('Mme', 'the Countess', 'Dona')] <- 'Mrs'
full$Title[full$Title %in% c('Mr', 'Capt', 'Major', 'Col', 'Don', 'Jonkheer')] <- 'Mr'
full$Title <- as.factor(full$Title)
```


```{r cache=TRUE}
ggplot(data = full[1:nrow(train),], mapping = aes(x = Title, y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Title impact survivor", x = "Title", y = "Count", fill = "Survived")
WOETable(X=full$Title[1:nrow(train)], Y=full$Survived[1:nrow(train)])
IV(X=full$Title[1:nrow(train)], Y=full$Survived[1:nrow(train)])
```




```{r}
full$Mother <- 'Non-mother'
full$Mother[as.integer(full$Age) > 20 & (!full$Title %in% c('Mr','Miss')) & as.integer(full$Parch) > 0] <- 'Mother'
full$Mother <- as.factor(full$Mother)

ggplot(data = full[1:nrow(train),], mapping = aes(x = factor(Mother), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Mother impact survivor", x = "Mother", y = "Count", fill = "Survived")
WOETable(X=full$Mother[1:nrow(train)], Y=full$Survived[1:nrow(train)])
IV(X=full$Mother[1:nrow(train)], Y=full$Survived[1:nrow(train)])
```







```{r cache=TRUE}
ggplot(data = full[1:nrow(train),], mapping = aes(x = factor(Pclass), y = ..count.., fill=factor(Survived))) + geom_bar(stat = 'count', width = 0.5, position = position_dodge(1)) + labs(title = "How Pclass impact survivor", x = "Pclass", y = "Count", fill = "Survived")
WOETable(X=factor(full$Pclass[1:nrow(train)]), Y=full$Survived[1:nrow(train)])
IV(X=factor(full$Pclass[1:nrow(train)]), Y=full$Survived[1:nrow(train)])
```






```{r results='hide'}
full$Pclass <- as.factor(full$Pclass)
full$Sex <- as.factor(full$Sex)
full$Survived <- as.factor(full$Survived)
```






```{r cache=TRUE}
ggplot(data = full[1:nrow(train),], mapping = aes(x = factor(Sex), y = ..count.., fill=factor(Survived))) + geom_bar(stat = 'count', position='dodge') + labs(title = "How Sex impact survivor", x = "Sex", y = "Count", fill = "Survived")
WOETable(X=factor(full$Sex[1:nrow(train)]), Y=full$Survived[1:nrow(train)])
IV(X=factor(full$Sex[1:nrow(train)]), Y=full$Survived[1:nrow(train)])
```





```{r cache=TRUE}
ggplot(data = full[1:nrow(train),], mapping = aes(x = factor(SibSp), y = ..count.., fill=factor(Survived))) + geom_bar(stat = 'count', position='dodge') + labs(title = "How SibSp impact survivor", x = "Sibsp", y = "Count", fill = "Survived")
WOETable(X=factor(full$SibSp[1:nrow(train)]), Y=full$Survived[1:nrow(train)])
IV(X=factor(full$SibSp[1:nrow(train)]), Y=full$Survived[1:nrow(train)])
```














```{r cache=TRUE}
ggplot(data = full[1:nrow(train),], aes(x = Fare, color=factor(Survived))) + geom_line(aes(file=..count..), stat = 'bin', binwidth=100)  + labs(title = "How Fare impace survivor", x = "Fare", y = "Count", fill = "Survived")
```





```{r cache=TRUE}
missing.embarked <- full[is.na(full$Embarked),]
missing.embarked[c('Pclass', 'Fare', 'Embarked')]
ggplot(full[!is.na(full$Embarked),], aes(x=Embarked, y=Fare, fill=factor(Pclass))) + geom_boxplot() + geom_hline(aes(yintercept=80), color='red', linetype='dashed', lwd=2) + scale_y_continuous(labels=dollar_format()) + theme_few()
```



从上图可知缺失Embark信息的两名乘客的Fare为$80，Pclass为1。而Fare为$80，Pclass为1的乘客最有可能从'C'登船，因此这里将缺失Embark信息的两名乘客的Embark设置为'C'


```{r}
full$Embarked[is.na(full$Embarked)] <- 'C'
full$Embarked <- as.factor(full$Embarked)
```






```{r cache=TRUE}
ggplot(data = full[1:nrow(train),], mapping = aes(x = factor(Embarked), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Pclass impact survivor", x = "Embarked", y = "Count", fill = "Survived")
```




```{r}
ticket.count <- aggregate(full$Ticket, by = list(full$Ticket), function(x) sum(!is.na(x)))
pclass.midean.fare <- aggregate(full$Fare, by = list(full$Pclass), FUN = function(x) median(x, na.rm = T))

full$Fare <- apply(full, 1, function(x) as.numeric(x['Fare']) / ticket.count[which(ticket.count[, 1] == x['Ticket']), 2])

full$Fare[which(full$Fare == 0)] <- apply(full[which(full$Fare == 0), ], 1, FUN = function(x) pclass.midean.fare[pclass.midean.fare[, 1] == x['Pclass'], 2])

full$TicketCount <- apply(full, 1, function(x) ticket.count[which(ticket.count[, 1] == x['Ticket']), 2])

ggplot(data = full[1:nrow(train),], mapping = aes(x = factor(TicketCount), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How TicketCount impact survivor", x = "TicketCount", y = "Count", fill = "Survived")

WOETable(X=full$TicketCount[1:nrow(train)], Y=full$Survived[1:nrow(train)])
IV(X=full$TicketCount[1:nrow(train)], Y=full$Survived[1:nrow(train)])


```

```{r}
# full$TicketCount <- factor(sapply(full$TicketCount, function(x) ifelse(x >=2, 'TRUE', 'FALSE')))
# ggplot(data = full[1:nrow(train),], mapping = aes(x = factor(TicketCount), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How TicketCount impact survivor", x = "TicketCount", y = "Count", fill = "Survived")
# 
# WOETable(X=full$TicketCount[1:nrow(train)], Y=full$Survived[1:nrow(train)])
# IV(X=full$TicketCount[1:nrow(train)], Y=full$Survived[1:nrow(train)])
```


```{r cache=TRUE}
df <- data.frame(Survived = full$Survived[1:nrow(train)])
df$Fare <- cut(full$Fare[1:nrow(train)], c(0, 20, 40, 60, 80, 100, 200, 300, 400, 1000), include.lowest = TRUE, right = FALSE)
ggplot(data = df, mapping = aes(x = factor(Fare), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Fare impact survivor", x = "Fare", y = "Count", fill = "Survived")
WOETable(X=df$Fare, Y=df$Survived)
IV(X=df$Fare, Y=df$Survived)
rm(df)
```






```{r cache=TRUE}
df <- data.frame(Survived = full$Survived[1:nrow(train)])
df$Fare <- cut(full$Fare[1:nrow(train)], c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 1000), include.lowest = TRUE, right = FALSE)
ggplot(data = df, mapping = aes(x = factor(Fare), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Fare impact survivor", x = "Fare", y = "Count", fill = "Survived")
WOETable(X=df$Fare, Y=df$Survived)
IV(X=df$Fare, Y=df$Survived)
rm(df)
```



```{r results='hide'}
#full$Fare <- cut(full$Fare, c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 1000), include.lowest = TRUE, right = FALSE)
```



```{r cache=TRUE}
df <- data.frame(Cabin <- sapply(full$Cabin[1:nrow(train)], FUN=function(x){ifelse(is.na(x), "X", "Y")}), Survived <- full$Survived[1:nrow(train)])
ggplot(data = df, mapping = aes(x = factor(Cabin), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Cabin impact survivor", x = "Cabin", y = "Count", fill = "Survived")
WOETable(X=df$Cabin, Y=df$Survived)
IV(X=df$Cabin, Y=df$Survived)
```




```{r cache=TRUE}
df <- data.frame(Cabin <- sapply(full$Cabin[1:nrow(train)], FUN=function(x){ifelse(is.na(x), "X", str_sub(x, start=1, end=1))}), Survived <- full$Survived[1:nrow(train)])
ggplot(data = df, mapping = aes(x = factor(Cabin), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Cabin impact survivor", x = "Cabin", y = "Count", fill = "Survived")
WOETable(X=df$Cabin, Y=df$Survived)
IV(X=df$Cabin, Y=df$Survived)
```



```{r results='hide'}
full$Cabin <- as.factor(sapply(full$Cabin, FUN=function(x){ifelse(is.na(x), "X", str_sub(x, start=1, end=1))}))
```









```{r results='hide'}
full$Family <- as.factor(full$SibSp + full$Parch)
```


```{r cache=TRUE}
ggplot(data = full[1:nrow(train),], mapping = aes(x = factor(Family), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Family impact survivor", x = "Family", y = "Count", fill = "Survived")
WOETable(X=full$Family[1:nrow(train)], Y=full$Survived[1:nrow(train)])
IV(X=full$Family[1:nrow(train)], Y=full$Survived[1:nrow(train)])
```




```{r cache=TRUE}
df <- data.frame(Family=sapply(full$Family[1:nrow(train)], function(x){if(as.integer(x)<=1){'Singleton'} else if(as.integer(x) < 4){'small'} else {'large'}}), Survived=full$Survived[1:nrow(train)])
ggplot(data = df, mapping = aes(x = factor(Family), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Family impact survivor", x = "Family", y = "Count", fill = "Survived")
WOETable(X=df$Family, Y=df$Survived)
IV(X=df$Family, Y=df$Survived)
```





# ```{r}
#age.model <- rpart(Age ~ Pclass + Sex + SibSp + Parch + Fare + Embarked + Title + Family, data=full[!is.na(full$Age), ], method='anova')
#full$Age[is.na(full$Age)] <- predict(age.model, full[is.na(full$Age), ])
# ```





```{r cache=TRUE}
ggplot(data = full[1:nrow(train),], aes(x = sapply(full$Age[1:nrow(train)], function(x){ifelse(is.na(x), 100, x)}), color=factor(Survived))) + geom_line(aes(file=..count..), stat = 'bin', binwidth=3)  + labs(title = "How Age impact survivor", x = "Age", y = "Count", fill = "Survived")
```





```{r cache=TRUE}
df <- data.frame(Age <- sapply(full$Age[1:nrow(train)], FUN=function(x){if(is.na(x)){" NA"} else if(x < 15){"0-15"} else if (x < 35) {" 15-35"} else if(x < 60) {" 35-60"}  else {"60"}}), Survived <- full$Survived[1:nrow(train)])
ggplot(data = df, mapping = aes(x = factor(Age), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Age impact survivor", x = "Age", y = "Count", fill = "Survived")
WOETable(X=df$Age, Y=df$Survived)
IV(X=df$Age, Y=df$Survived)
```





```{r cache=TRUE}
df <- data.frame(Age <- sapply(full$Age[1:nrow(train)], FUN=function(x){if((!is.na(x)) && (x<18)){"teenager"} else {"adult"}}), Survived <- full$Survived[1:nrow(train)])
ggplot(data = df, mapping = aes(x = factor(Age), y = ..count.., fill=factor(Survived))) + geom_bar(stat = "count", position='dodge') + labs(title = "How Age impact survivor", x = "Age", y = "Count", fill = "Survived")
WOETable(X=df$Age, Y=df$Survived)
IV(X=df$Age, Y=df$Survived)
```



```{r}
full$Age <- as.factor(sapply(full$Age, function(x){if(is.na(x)){" N-A"} else if(x < 15){"0-15"} else if (x < 35) {" 15-35"} else if(x < 60) {" 35-60"}  else {"old"}}))
```





```{r}
set.seed(256)
cv.train.sample <- sample(1:nrow(train), as.integer(0.5 * nrow(train)), replace = TRUE)
cv.train <- full[cv.train.sample,]
cv.test <- full[1:nrow(train),][-cv.train.sample,]
cv.test_true <- full$Survived[1:nrow(train)][-cv.train.sample]
```


```{r "training model"}
full$Result <- full$Survived
levels(full$Result) <- c(0, 1)
full$Result <- as.integer(full$Result) - 1

train.data <- full[1:nrow(train),]

model.features <- c('Age', 'Fare', 'Cabin', 'Embarked', 'Pclass', 'Sex', 'Family', 'Title', 'Mother', 'TicketCount')
model.formula <- as.formula(paste('Survived ~ ', paste(model.features, collapse=' + ')))


lrmodel <- glm(formula=model.formula, data=train.data, family=binomial)

rfmodel <- randomForest(formula=model.formula, data=train.data, ntree=2000)
plot(rfmodel)

svmmodel <- svm(formula=model.formula, data=train.data)

citmodel <- cforest(formula=model.formula, data=train.data, controls=cforest_unbiased(ntree=1000, mtry=3))


gbmmodel <- gbm(
                Result ~ Age + Fare + Cabin + Embarked + Pclass + Sex + Family + Title + Mother,
                data = train.data,
                distribution = "adaboost",
                interaction.depth = 5,
                n.trees = 8000,
                shrinkage = 0.001,
                bag.fraction = 0.8,
                n.cores = 8,
                cv.folds = 5,
                verbose = FALSE)
gbm.perf(gbmmodel)

rpartmodel <- rpart(model.formula,
             data = train.data,
             method = "class")




summary(lrmodel)
summary(rfmodel)
summary(svmmodel)
summary(citmodel)
summary(gbmmodel)
summary(rpartmodel)

print(lrmodel)
print(rfmodel)
print(svmmodel)
print(citmodel)
print(gbmmodel)
print(rpartmodel)


```


```{r 'Definition of assemble predict function'}
assemble.predict <- function(data) {
  assemble.result <- data.frame(Dummy = rep(0, nrow(data)))
  
  assemble.result$LinearRegression <- factor((ifelse(predict(lrmodel, newdata=data, type="response") > 0.5, 1, 0)), levels = c(0, 1))
  assemble.result$RandomForest <- predict(rfmodel, newdata=data, type="response", ntree = 2000)
  assemble.result$SVM <- predict(svmmodel, newdata=data, type="response")
  assemble.result$CIT <- predict(citmodel, newdata=data, type="response")
  assemble.result$GBM <- factor(ifelse(predict(gbmmodel, newdata=data, type="response", n.trees = 2564) > 0.5, 1, 0), levels = c(0, 1))
  assemble.result$RPart <- predict(rpartmodel, newdata=data, type = "class")
  
  assemble.result <- assemble.result[, -1]
  threshold <- as.integer((ncol(assemble.result) + 1)/2)
  assemble.result$Ensemble <- factor(apply(assemble.result, 1, FUN = function(x) ifelse(sum(as.integer(x)) >= threshold, 1, 0)), levels = c(0, 1))

  return(assemble.result)
}
```


```{r 'Definition of cross validation function'}
cross.validation <- function(predict.data, true.data) {
  sapply(colnames(predict.data), function(name){
    print(name)
    print(paste(' Recall:', Recall(true.data, predict.data[[name]])))
    print(paste(' Precision:', Precision(true.data, predict.data[[name]])))
    print(paste(' Accuracy', Accuracy(predict.data[[name]], true.data)))
    print(paste(' AUC', AUC(predict.data[[name]], true.data)))
    print('')
  })
}
```

```{r 'Cross validation'}
cv.predict <- assemble.predict(cv.test)
cross.validation(cv.predict, cv.test_true)
```


```{r 'Predicting'}
test.data <- full[(nrow(train)+1):(nrow(train)+nrow(test)), model.features]
test.predict <- assemble.predict(test.data)

test.result <- data.frame(full$PassengerId[(nrow(train)+1):(nrow(full))], Survived=test.predict$RPart)
colnames(test.result) <- c('PassengerId', 'Survived')
head(test.result, 10)
```

```{r 'Predict result saving'}
write.csv(test.result, file="result.csv", row.names=FALSE, quote=FALSE)
```










